### ISSUE TITLE
効果音をつける

### ISSUE THREAD

**Issue by MaxMEllon** [MaxMEllon/Bong#1]
概要

---

バーを動かしたとき，ボールを動かしたときなど何らかの動きがあったときに音を鳴らす．

音を鳴らしたい箇所リスト

---

- [ ] バーを動かしたとき
- [ ] ボールがバーに触れたとき
- [ ] ミスした（ボールがバーを通り超えて左右の壁に触れた）とき

**Comment by fentok** [comment]
個人的にはミスをした時も音を鳴らしたほうが分かりやすいと思います

**Comment by MaxMEllon** [comment]
なるほど！ その意見を取り入れます！

**Comment by MaxMEllon** [comment]
実装されていることを確認し，マスターにマージしました！！！

:tada::tada::tada::tada::tada::tada::tada::tada:
