### ISSUE TITLE
ブラインドボール

### ISSUE THREAD

**Issue by MaxMEllon** [MaxMEllon/Bong#2]
概要

---

何らかの条件を見たした時，ボールを一時的に見えなくする．

**Comment by 14t281** [comment]
出来るならプレイヤーがキーを押したとき、任意のタイミングで消えるようにしたいです。バーの近くでは消えない様にしたり、消せる時間に制限とかをかけた上で。

**Comment by MaxMEllon** [comment]
なるほど．跳ね返すと技ポイントなどがたまり，それが１００％になったとき 5秒間の間消せるとか面白そうですね．

**Comment by MaxMEllon** [comment]
実装されていることを確認し，マスターにマージしました！！！

🎉🎉🎉🎉🎉🎉🎉🎉
